#!/usr/bin/env bash
# overlay-regen-patches.sh <base-verus_builtin_macros-version>
#
# Regenerates the overlay resync assets (patches/, files/, manifest.txt) by
# diffing the *current* committed overlay against pristine upstream
# `verus_builtin_macros` at <base-version>.
#
# Run this after hand-fixing source/builtin_macros_overlay/src to compile
# against a new upstream release (i.e. when overlay-resync.sh reported a
# failed patch because upstream drifted). The regenerated assets let
# overlay-resync.sh reproduce the fixed overlay for that version and forward.
#
# The delta shape is derived, not hardcoded, so it self-adjusts: e.g. once
# upstream ships the contrib::hooks seam, the overlay's mod.rs matches upstream
# (no patch emitted) and its hooks.rs equals upstream's (not copied as an
# added file) — the delta shrinks automatically.
#
# Classification (per file under src/, plus Cargo.toml handled specially):
#   in pristine, not in overlay  -> DELETED  (recorded in manifest.txt)
#   in overlay, not in pristine  -> ADDED    (copied verbatim into files/)
#   in both, differ              -> PATCHED  (unified diff into patches/)
#   Cargo.toml                   -> never patched here: overlay-resync.sh
#                                   derives it from upstream's manifest
set -euo pipefail

VERSION="${1:?usage: overlay-regen-patches.sh <verus_builtin_macros-version>}"
REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
OVERLAY="$REPO_ROOT/source/builtin_macros_overlay"
RESYNC="$OVERLAY/resync"

# Fetch pristine upstream.
WORK="$(mktemp -d)"; trap 'rm -rf "$WORK"' EXIT
cat > "$WORK/Cargo.toml" <<EOF
[package]
name = "fetch_bm"
version = "0.0.1"
edition = "2021"
[dependencies]
verus_builtin_macros = "=$VERSION"
[lib]
path = "src/lib.rs"
[workspace]
EOF
mkdir -p "$WORK/src"; touch "$WORK/src/lib.rs"
( cd "$WORK" && cargo fetch --quiet )
PRISTINE=""
for d in "$HOME"/.cargo/registry/src/*/"verus_builtin_macros-$VERSION"; do
  [ -d "$d" ] && PRISTINE="$d"
done
[ -n "$PRISTINE" ] || { echo "FATAL: pristine verus_builtin_macros-$VERSION not found" >&2; exit 1; }
echo "pristine: $PRISTINE"

# Reset the asset dirs.
rm -rf "$RESYNC/patches" "$RESYNC/files"
mkdir -p "$RESYNC/patches" "$RESYNC/files"
: > "$RESYNC/manifest.txt"
{
  echo "# Files deleted from upstream verus_builtin_macros in the overlay."
  echo "# Generated by overlay-regen-patches.sh against $VERSION."
  echo "# One path per line, relative to the crate root."
} >> "$RESYNC/manifest.txt"

added=0 patched=0 deleted=0

# DELETED + PATCHED: iterate pristine files.
while IFS= read -r pf; do
  rel="${pf#"$PRISTINE"/}"
  [ "$rel" = "Cargo.toml" ] && continue   # templated separately
  of="$OVERLAY/$rel"
  if [ ! -e "$of" ]; then
    echo "$rel" >> "$RESYNC/manifest.txt"
    deleted=$((deleted+1))
  elif ! diff -q "$pf" "$of" >/dev/null 2>&1; then
    name="$(echo "$rel" | sed 's|/|__|g').patch"
    # diff exits 1 when files differ (the expected case); don't trip set -e.
    diff -u --label "a/$rel" --label "b/$rel" "$pf" "$of" > "$RESYNC/patches/$name" || true
    patched=$((patched+1))
  fi
done < <(find "$PRISTINE/src" -type f; echo "$PRISTINE/Cargo.toml")

# ADDED: iterate overlay files not in pristine (src/ only; root files like
# build.rs / contrib_hooks_provider.rs are overlay-owned and never touched by
# resync, so they are excluded here).
while IFS= read -r of; do
  rel="${of#"$OVERLAY"/}"
  if [ ! -e "$PRISTINE/$rel" ]; then
    mkdir -p "$RESYNC/files/$(dirname "$rel")"
    cp "$of" "$RESYNC/files/$rel"
    added=$((added+1))
  fi
done < <(find "$OVERLAY/src" -type f)

echo "regenerated: $patched patched, $added added, $deleted deleted"
echo "review resync/ and commit."
